import os
from functools import wraps

from dotenv import load_dotenv
from flask import Flask, redirect, url_for, session, request, render_template, jsonify, send_from_directory, Blueprint
from google.auth.transport import requests as google_requests
from google.oauth2 import id_token
from google_auth_oauthlib.flow import Flow

from db import execute_query, init_db, error_log
from ingest import run_ingestion, ingestion_status
from search_service import search_documents, get_common_tags
from processor import get_sharded_path

load_dotenv()

app = Flask(__name__)
app.secret_key = os.getenv("FLASK_SECRET_KEY", "secret-key")

# Blueprint with requested prefix
bp = Blueprint('docsearchpro', __name__, template_folder='templates')

# OAuth 2.0 Configuration
CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")
REDIRECT_URI = os.getenv("GOOGLE_REDIRECT_URI")

# Allow insecure transport for local development
os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'


def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'user' not in session:
            return redirect(url_for('docsearchpro.login'))
        return f(*args, **kwargs)

    return decorated_function


def admin_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'user' not in session or session['user'].get('role') != 'admin':
            return "Unauthorized", 403
        return f(*args, **kwargs)

    return decorated_function


@bp.route('/')
@login_required
def home():
    document_count = execute_query("SELECT COUNT(*) FROM documents")[0]['count']
    folder_count = execute_query("SELECT COUNT(*) FROM folders")[0]['count']
    return render_template('home.html', document_count=document_count, folder_count=folder_count)


@bp.route('/login')
def login():
    flow = Flow.from_client_config(
        {"web": {"client_id": CLIENT_ID, "client_secret": CLIENT_SECRET,
                 "auth_uri": "https://accounts.google.com/o/oauth2/auth",
                 "token_uri": "https://oauth2.googleapis.com/token"}},
        scopes=['openid', 'https://www.googleapis.com/auth/userinfo.email',
                'https://www.googleapis.com/auth/userinfo.profile']
    )
    flow.redirect_uri = REDIRECT_URI
    
    # We explicitly use a state but might need to handle the code_verifier
    # generated by the flow if the library defaults to PKCE.
    authorization_url, state = flow.authorization_url(prompt='consent')
    
    session['state'] = state
    # If the flow object generated a code_verifier, we MUST save it.
    if hasattr(flow, 'code_verifier'):
        session['code_verifier'] = flow.code_verifier
        
    return redirect(authorization_url)


@bp.route('/callback')
def callback():
    state = session.get('state')
    code_verifier = session.get('code_verifier')
    
    if not state:
        return "Session state missing. Please try logging in again.", 400

    flow = Flow.from_client_config(
        {"web": {"client_id": CLIENT_ID, "client_secret": CLIENT_SECRET,
                 "auth_uri": "https://accounts.google.com/o/oauth2/auth",
                 "token_uri": "https://oauth2.googleapis.com/token"}},
        scopes=['openid', 'https://www.googleapis.com/auth/userinfo.email',
                'https://www.googleapis.com/auth/userinfo.profile'],
        state=state
    )
    flow.redirect_uri = REDIRECT_URI
    
    # Restore the code_verifier if it was saved
    if code_verifier:
        flow.code_verifier = code_verifier
    
    # Ensure authorization_response uses https if REDIRECT_URI is https
    # This handles cases where Flask is behind a reverse proxy or SSL terminator
    authorization_response = request.url
    if REDIRECT_URI.startswith('https') and authorization_response.startswith('http:'):
        authorization_response = authorization_response.replace('http:', 'https:', 1)

    try:
        flow.fetch_token(authorization_response=authorization_response)
    except Exception as e:
        error_log("Failed to fetch token", str(e))
        return f"Failed to fetch token: {str(e)}", 400

    credentials = flow.credentials
    id_info = id_token.verify_oauth2_token(credentials.id_token, google_requests.Request(), CLIENT_ID)

    email = id_info.get('email')
    if "@rmutsb.ac.th" not in email:
        return "Please login using @rmutsb.ac.th email"

    user = execute_query("SELECT * FROM users WHERE email = %s", (email,))
    if not user:
        execute_query("""
                      INSERT INTO users (email, first_name, last_name, display_name, picture, role)
                      VALUES (%s, %s, %s, %s, %s, 'viewer')
                      """,
                      (email, id_info.get('given_name', ''), id_info.get('family_name', ''), id_info.get('name', ''),
                       id_info.get('picture', ''),), fetch=False)
        user = execute_query("SELECT * FROM users WHERE email = %s", (email,))

    session['user'] = {
        'id': str(user[0]['id']),
        'email': user[0]['email'],
        'role': user[0]['role']
    }
    return redirect(url_for('docsearchpro.home'))


@bp.route('/search')
@login_required
def search():
    query = request.args.get('query', '')
    if not query:
        return jsonify([])

    tag_ids = request.args.getlist('tags', type=int)
    limit = request.args.get('limit', default=20, type=int)
    results = search_documents(query, tag_ids=tag_ids, limit=limit)

    execute_query("""
                  INSERT INTO search_logs (user_id, search_query, search_hidden, search_protected)
                  VALUES (%s, %s, false, false)
                  """, (session['user']['id'], query), fetch=False)

    return jsonify(results)


@bp.route('/tags')
@login_required
def tags():
    return jsonify(get_common_tags())


@bp.route('/ingest', methods=['GET', 'POST'])
@admin_required
def ingest():
    if request.method == 'GET':
        return render_template('ingest.html')
    
    folder_link = request.form.get('folder_link')
    mode = request.form.get('mode', 'Fast')
    
    started = run_ingestion(folder_link, mode)
    if started:
        return "Ingestion started", 202
    else:
        return "Ingestion already running", 409

@bp.route('/ingest/status')
@admin_required
def ingest_status_api():
    return jsonify(ingestion_status)


@bp.route('/preview/<drive_id>/<int:page_number>')
@login_required
def preview(drive_id, page_number):
    sharded_dir = get_sharded_path(os.path.join('static', 'previews'), drive_id)
    return send_from_directory(sharded_dir, f'page_{page_number}.png')


@bp.route('/init-db')
@admin_required
def init_database():
    init_db()
    return "Database initialized", 200


# Redirect root to blueprint
@app.route('/')
def root_redirect():
    return redirect(url_for('docsearchpro.home'))


app.register_blueprint(bp, url_prefix='/DocSearchPro')

if __name__ == '__main__':
    app.run(port=9010, debug=True)
